-- Users table (extends Supabase Auth)
CREATE TABLE public.profiles (
  id UUID REFERENCES auth.users(id) PRIMARY KEY,
  full_name TEXT,
  avatar_url TEXT,
  subscription_status TEXT DEFAULT 'free', -- 'free', 'premium', 'canceled'
  stripe_customer_id TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Daily Signals (Content)
CREATE TABLE public.daily_signals (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  date DATE NOT NULL,
  language VARCHAR(5) NOT NULL DEFAULT 'en', -- 'en', 'sk', 'cs'
  theme TEXT NOT NULL,
  focus TEXT NOT NULL,
  affirmation TEXT NOT NULL,
  script TEXT, -- Full text for TTS
  push_text TEXT, -- Notification text
  audio_url TEXT, -- URL to audio file (e.g. Supabase Storage / R2)
  status TEXT DEFAULT 'draft', -- 'draft', 'generated', 'published'
  audio_duration INTEGER, -- In seconds
  generation_metadata JSONB, -- Model info, etc.
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  UNIQUE(date, language) -- Ensures one signal per day per language
);

-- User Progress (Tracking completed days)
CREATE TABLE public.user_progress (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES public.profiles(id) NOT NULL,
  signal_id BIGINT REFERENCES public.daily_signals(id) NOT NULL,
  completed_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  UNIQUE(user_id, signal_id) -- User can complete a signal only once
);

-- Enable Row Level Security (RLS)
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.daily_signals ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_progress ENABLE ROW LEVEL SECURITY;

-- Policies for Profiles
CREATE POLICY "Public profiles are viewable by everyone." 
  ON public.profiles FOR SELECT USING (true);

CREATE POLICY "Users can insert their own profile." 
  ON public.profiles FOR INSERT WITH CHECK (auth.uid() = id);

CREATE POLICY "Users can update own profile." 
  ON public.profiles FOR UPDATE USING (auth.uid() = id);

-- Policies for Daily Signals
-- Anyone can read signals (or restrict to premium users later)
CREATE POLICY "Daily signals are viewable by everyone." 
  ON public.daily_signals FOR SELECT USING (true);

-- Only admins/service_role can insert/update signals (You will use the dashboard or admin API)
-- (By default, no public insert/update policy means only service_role can modify)

-- Policies for User Progress
CREATE POLICY "Users can view their own progress." 
  ON public.user_progress FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "Users can insert their own progress." 
  ON public.user_progress FOR INSERT WITH CHECK (auth.uid() = user_id);
